### PR TITLE
Changed stderr from displaying "err:" to red color

### LINKED ISSUE #140: Change the launcher game output stderr to be different colour
instead of prefixing with `err:` would probably be nicer to just have the text be a lightish red

### PR DESCRIPTION
**Pull request by devtopher**
Hello! 

I am a new developer and wanted to give this a shot. I'm not sure if the logic works on simply changing the "err: " + data to data.style.color = "#color" but I gave it a shot. This is my first pull request so I'm not totally sure I did the process right. If theres something different I should do I'd love any direction. Thanks!

closes #140

Chris

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Does not work correctly, results in exception:
```
17:16:57.612 › TypeError: Cannot set properties of undefined (setting 'color')
    at /home/hhyyrylainen/Projects/Thrive-Launcher/src/thrive_runner.js:103:40
    at CallbacksRegistry.apply (/home/hhyyrylainen/Projects/Thrive-Launcher/node_modules/@electron/remote/dist/src/renderer/callbacks-registry.js:54:29)
    at /home/hhyyrylainen/Projects/Thrive-Launcher/node_modules/@electron/remote/dist/src/renderer/remote.js:345:23
    at EventEmitter.<anonymous> (/home/hhyyrylainen/Projects/Thrive-Launcher/node_modules/@electron/remote/dist/src/renderer/remote.js:327:13)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:1017)
```
(edit: I pasted in the wrong thing, fixed now)

in the callback you modified `data` is a string. You probably need to adjust the code in appendMessage so that you can specify with a parameter the custom text colour.

**Comment by devtopher** [comment]
Thanks for looking at it and giving me some feedback. I will see if I can sort it out 😀

**Comment by devtopher** [comment]
So I took another stab at it but am running into an issue. Maybe this is just too far over my head but my thought process was to follow what you said and add a color parameter to appendMessage, however appendMessage is this: const appendMessage = prepareGameOutputWriteFunction(status);
when I try to set up a similar structure in a test environment and then do appendMessage("anythinghere") it tells me that appendMessage is not a function.

My thought was to change prepareGameOutputWriteFunction(status, color) to take the color parameter and then style message within that function. Then when you call appendMessage for the stderr I could just add "red" as a parameter for appendMessage and it would work, however, I'm not sure that is the case. I may have bitten off more than I can chew and if thats true feel free to let me know and I'll leave this issue for someone else. 

Thanks for your time.

Chris

**Comment by devtopher** [comment]
Ok thats helpful. That is the section of code I was looking in and figured out I needed to modify message. Here's what I have so far: 
return (text, color) => {

        const message = document.createElement("div");
        message.textContent = text;
        if (color){
            message.style.color = color
        }
        

I think that works, but the question I have is where do I actually pass in "red" for the stderr.

**Comment by hhyyrylainen** [comment]
I think you initially found that place correctly. So now that you have the second parameter added, making changes in `thrive.stderr.on("data", (data) => {` to pass in the colour, should probably work now.

**Comment by devtopher** [comment]
thrive.stderr.on("data", (data) => {
        appendMessage(data, "red");

This doesnt throw any errors, but I'm not sure the color is going to get passed to the right place. Does this make sense?

**Comment by devtopher** [comment]
Or I guess it may need to be in as a parameter for the arrow function.

**Comment by hhyyrylainen** [comment]
> thrive.stderr.on("data", (data) => {
appendMessage(data, "red");

Looks pretty correct to me.
You can't add a parameter to the arrow function, because that is a callback passed to the nodejs child process message stream. So you can't add a new parameter there unless you modify nodejs source code...

**Comment by devtopher** [comment]
I think I got it this time! I had some trouble with the linter but got that sorted out. If this does not work please let me know and I will keep trying. Thanks so much for your patience as I figure all of this out!

**Review by hhyyrylainen — APPROVED** [review]
This seems to work perfectly now. And also the red colour looks good in the game output, which surprised me a bit as I thought my next suggestion would be to change the colour to a lighter red. But I think this is now good to go.

**Comment by devtopher** [comment]
Thank you! I'm glad it looks good, and I appreciate all the help you gave
me in getting this accomplished.

**Pull request merged**
